spring:
  datasource:
    url: jdbc:mysql://studmysql01.fhict.local/dbi507161
    username: 'dbi507161'
    password: 'rental_tycoon'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

file:
  upload-dir: uploads

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

jwt:
  secret: ys9qm39QC0aI9F3xMmU/v+ivnWGq4ngRDYl13xoMngoyG3xdW/AX+HUcb6/TkykASpUaGBGWI1clmJqjYEsQAQ==
